name: Java CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - name: Set up JDK 8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 8
      - uses: actions/cache@v2.1.2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Move built jars
        run: |
          mkdir staging
          cp -r bukkit/target staging/bukkit
          cp -r bungee/target staging/bungee
          cp -r common/target staging/common
          cp -r target staging/configapi
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging